### ISSUE TITLE
New UI makes the text flow out of screen which comes after hovering.

### ISSUE THREAD

**Issue by Rtizer-9** [Cimbali/CleanLinks#100]
On my 13.3" laptop the new UI is acting weirdly.

Clicking on "http requests" and "Redirected to embedded url" flickers the UI continuously on my screen maybe because it goes into some loop for accommodating the text into the current screen size.

Hovering over the URLs also doesn't show the full URLs all time. It only shows full text(the last cleaned url) when screen has enough space for it.

I've made some changes to firefox UI using about:config options if that's of any help to you.

It would be helpful if you describe the new options(buttons) in the wiki with some clear examples to understand the possible cases.

**Comment by jawz101** [comment]
same w/ me on a 22" desktop monitor.  It's flickering so much it's unusable

**Comment by Cimbali** [comment]
Does it flicker all of the time or when clicking buttons?

**Comment by jawz101** [comment]
looks like it only happens when it has nothing to display

ex: go to about:blank in the address bar and then click on the icon

**Comment by Rtizer-9** [comment]
Not all the time, only when clicking those exact two options; at least in my case.

**Comment by Cimbali** [comment]
OK I will try to make the popup size fixed. Fix should be on AMO in a couple of minutes.

The explanation of the buttons etc if here: <https://github.com/Cimbali/CleanLinks/wiki/Interface#cleanlinks-popup>

**Comment by Rtizer-9** [comment]
Oh, sorry. I should've looked before.

**Comment by Cimbali** [comment]
Ah I remember now why it wasn’t fixed already… it breaks the popup (hidden overflow) when in the overflow menu. It’ll probably be a bit of a harder fix.

**Comment by Rtizer-9** [comment]
Take your time. :)

**Comment by Cimbali** [comment]
@Rtizer-9 @jawz101 can one of you test 52aac51 ? Otherwise report your OS and Firefox versions so I can test it before releasing?

Testing it is pretty easy:
1. The zip is available here: <https://github.com/Cimbali/CleanLinks/archive/52aac5152d39e5a429bbebd878495c3080fe5155.zip>
2. Unzip it
3. Open `about:debugging#/runtime/this-firefox` and click `Load Temporary Add-on…`
4. Point Firefox to the addon/manifest.json file that you just unzipped.

**Comment by Rtizer-9** [comment]
I think as far as I can see the both issues are solved. If you can make the entries have a colour code as before it would be more accessible. There are lots of space left in the popup and it's too big for my screen. I can perfectly work with it so it's not huge issue. It's just that the previos UI fitted and looked perfect in comparison to this, at least at this stage.

**Comment by Cimbali** [comment]
Thanks @Rtizer-9 ! Can you also send a screenshot of the popup on your laptop so I can get a feel of what it looks like?

I think the popup size might become configurable in the future, because links to clean are quite big, so a big popup allows to see them entirely. On the other hand smaller resolutions might have trouble with a big popup (we should be good until 800px wide).

**Comment by Rtizer-9** [comment]
I wanted to do that in the first comment itself but the moment I press button the popup menu gets closed.

**Comment by Cimbali** [comment]
Ah yes. There is an option to deactivate that. It’s acalled “Disable popup auto-hide” accessible through the `…` button in the top right corner of the Developer Tools.

**Comment by Rtizer-9** [comment]
https://ibb.co/yR3j8Ly
https://ibb.co/n6L39q6
