### ISSUE TITLE
Google images original image?

### ISSUE THREAD

**Issue by khabib227** [Cimbali/CleanLinks#101]
Few days ago, if I click in any thumb, open the original image (original resolution) but now open the modal window (popunder). I want the original image, how to fix it? Someone can help please?

**Comment by Cimbali** [comment]
Hi @khabib227. Here’s what I understand you’re trying to do, please tell me f I’m wrong:
- go to google image results
- right-click a small image
- click « open the original image (original resolution) »

However I don’t have this option on google images (both on v66 an d v73), because I have the [big right-hand side panel layout](https://support.google.com/websearch/thread/13571091?hl=en). Therefore I usually:
- click the image to see it bigger in the search results
- right-click the big image and click « View Image » or « Copy Image Location ».

I’m also not sure that CleanLinks is causing this as we don’t really interfere with popups/popunders. In order to see the problem you have, can you specify which browser (and version) you’re using?

Here’s a couple generic tips to help you:
- You can disable the add-on on a single tab by opening the popup and clicking the big icon or the on-off buton. This should help you identify whether CleanLinks or another add-on is causing the issue.
- Clicking on the popup shows a history of cleaned links. You can empty the list by clicking on the trash icon, then click on « open the original image (original resolution) » and see if a cleaned link shows up in the list. If so:
    - selecting the cleaned link and doing ctrl+c (or cmd+c on macOS) will copy the clean and dirty links, so you can share them here
    - selecting the cleaned link allows you to whitelist it (and other interactions) using the buttons at the bottom of the popup.

**Comment by khabib227** [comment]
Hi @Cimbali thanks the informations, I'm using FF 67 with last CL, what I want is open original images directely with left click, without google intermediate page, with CL enabled, left click on thumb open intermediate page, middle click open original, with CL disabled, left or middle clicks open intermediate page. To me just middle click opening original is very good, I just want to know if is possible with left click also. Thanks

**Comment by Cimbali** [comment]
So what seems to me is happening is that all thumbnails are links to an intermediate page, such as:
  https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.abc-collectivites.com%2F4782-large_default%2Fbarriere-de-circulation-police-2-m.jpg&imgrefurl=https%3A%2F%2Fwww.abc-collectivites.com%2F5828-barriere-de-circulation-police-2-m.html&tbnid=DczWCPCAzIvmzM&vet=12ahUKEwip_Yj9_sLoAhVBEhoKHW7ZBkAQMygCegUIARCkAg..i&docid=8CcM2bxe0eaQRM&w=610&h=458&q=barri%C3%A8re

When you click that link to a new tab (middle click / ctrl + click) this link gets used, so CL sees the request for the new page and cleans it.

When you simply click on the thumbnail, the link doesn’t get loaded. Instead some javascript magic happens on google’s side to change the current page to the intermediate page. In particular, no request containing the image is initiated (or we would catch it and clean it).

The best way, I believe, to have left click open the image is simply to disable javascript on google’s search results.

**Comment by khabib227** [comment]
` Instead some javascript magic happens `

Google is specialist in javascript magics

` I believe, to have left click open the image is simply to disable javascript on google’s search results`

The problem is which change site version, and in this version the thumbs do not link to original images, instead link to source page. But anyway thanks so much your attention and explanation.

**Comment by Cimbali** [comment]
CleanLinks will successfully prevent javascript on these types of links in the next release. So left click on a google image thumbnail will go directly through to the image. An option to disable this behaviour (i.e. allow javascript) is available in the rules editor.
