### ISSUE TITLE
Are whitelists implemented properly in needed cases?

### ISSUE THREAD

**Issue by Rtizer-9** [Cimbali/CleanLinks#120]
It's an issue which I encountered very earlier and would like you to cross check if it's even legitimate or not.

I think I remember from some changelog that you added ClearUrls' filters as requested by user, but what I noticed was it has several whitelist(exceptions section) entries which I think has not been implemented in cleanlinks. 

Specifically, the issue is that, there are some parameters which should not be removed when working on certain websites but good to remove globally. One eg I noticed was on Facebook.

You can try to visit urls which have parameters listed under the "exceptions" section on https://kevinroebert.gitlab.io/ClearUrls/data/data.minify.json , and check if cleanlinks allows them (which it should instead of cleaning) or not.

**Comment by Cimbali** [comment]
Yes. the whitelist in ClearUrls are expressed in a way that is way too broad for CleanLinks to import. To take your example of the `ref` on facebook photos, which has since been added to the CleanLinks default rules, the ClearUrls rules specify that **none** of the facebook specific-rules applies on **any** page matching the following:

	".*(facebook\\.)\\w{2,}.*(\\/plugins\\/).*"
	".*(facebook\\.)\\w{2,}.*(\\/dialog\\/share).*"
	".*(facebook\\.)\\w{2,}.*(\\/groups\\/member_bio\\/bio_dialog\\/).*"
	".*(facebook\\.)\\w{2,}.*(\\/photo\\.php\\?).*"
	".*(facebook\\.)\\w{2,}.*(\\/ajax\\/).*"
	".*(facebook\\.)\\w{2,}.*(\\/privacy\\/specific_audience_selector_dialog\\/).*"
	".*(facebook\\.)\\w{2,}.*(\\/photo\\/download\\/).*"

So  `ref` can still be used to track you on any ajax calls, even though they are only required fo `/photo.php`. If you want to go over each page to find out which parameter should be kept, I can integrate these changes, but I don’t have the time to do this exploration now − and I think it it somewhat low priority as we only ran into 1 issue with `/photo.php?ref=`

**Comment by Rtizer-9** [comment]
Oh, OK. I've also encountered the issue various times on gmail as you can the list for it is also very long. But yeah, I think its fine. Just wanted to let you know. Its just that I have several other privacy addons installed and also keep fiddling with the advance/privacy settings on a regular basis which leads me to visit these exception filled Urls regularly.

Hope you're doing well.
