### ISSUE TITLE
Relation to another extension CleanLinks

### ISSUE THREAD

**Issue by shanepeleg** [Cimbali/CleanLinks#131]
Hi

Would you mind clarifying what the relation between this project, its code base and you and the extension CleanLinks [0] by @diegocr and its developer(s) is?  Thank you.

[0] https://github.com/diegocr/CleanLinks

**Comment by diegocr** [comment]
It is a fork of mine, i am not involved in the development (for the good and the bad ;))

**Comment by Cimbali** [comment]
Yes, this is a fork that happened when the original CleanLinks needed to be rewritten in depth to transition from the XUL to WebExtension model of Firefox extensions. This fork was initially just a rewrite with the exact same features, hence the same name. Over the years some different features or mechanisms were added to try and improve usability (which is a hard problem !).

This used to be visible by the fact that this repo was forked from the other one. I asked this repo be made standalone to gain some visibility in github (otherwise only the root repo shows up in searches), but I apparently did not document the now less visible inheritance.

You’ll find this text on all legacy documentations of Firefox add-ons:

> Support for extensions using XUL/XPCOM or the Add-on SDK was removed in Firefox 57, released November 2017. […]
>
> Starting from Firefox 53, no new legacy add-ons will be accepted on addons.mozilla.org (AMO) for desktop Firefox and Firefox for > Android.
>
> Starting from Firefox 57, only extensions developed using WebExtensions APIs will be supported on Desktop Firefox and Firefox > for Android. 

See also the announcement of the end of compatiblity:
https://blog.mozilla.org/addons/2017/08/10/upcoming-changes-compatibility/

**Comment by shanepeleg** [comment]
Thank both of you for clarifying.
