### ISSUE TITLE
Whitelist selection ignored (?)

### ISSUE THREAD

**Issue by alekksander** [Cimbali/CleanLinks#14]
reproduce:
**1.** go: https://www.trojmiasto.pl/wiadomosci/Tak-powstaje-druga-kladka-na-Motlawie-n124071.html

**2.** try to open images from article (could be the first one)

**3.** results in internal non existing page

**4.** go back one page, whitelist latest entry

expected behavior:
clicking image will js zoom pic, or go to http pic location

what happens:
whitelist is ignored or regex to complex. no matter how many times its whitelisted we are back to internal non existing page.

**Comment by Cimbali** [comment]
Ok so in your example the link is:
`javascript:displayWindowzdjecie('/_misc/zdj_wym.php?url_zdjecie=https://static2.s-trojmiasto.pl/zdj/c/n/9/2079/1100x0/2079199-Wizualizacja-obrotowej-kladki-Sw-Ducha.jpg',1100,778);`

The expected cleaning is:
<https://static2.s-trojmiasto.pl/zdj/c/n/9/2079/1100x0/2079199-Wizualizacja-obrotowej-kladki-Sw-Ducha.jpg>

However we get some garbage at the end:
<https://static2.s-trojmiasto.pl/zdj/c/n/9/2079/1100x0/2079199-Wizualizacja-obrotowej-kladki-Sw-Ducha.jpg',1100,778);>

Also whitelisting the link from cleaned link history appears to not add the domain to the domains list, and manually adding `www.trjmiasto.pl` or `static2.s-trojmiasto.pl` to the ignored domain list does not work.

This seems to all be part of the same bug: we should identify the string `'/_misc/zdj_wym.php?url_zdjecie=https://static2.s-trojmiasto.pl/zdj/c/n/9/2079/1100x0/2079199-Wizualizacja-obrotowej-kladki-Sw-Ducha.jpg'` as the link instead of until the end of the javascript function call.
