### ISSUE TITLE
Google search results add some redirect in the sites

### ISSUE THREAD

**Issue by jawz101** [Cimbali/CleanLinks#149]
If I search for the word "test"

Hover over any search result before you click it

The first result in the page is for speedtest.net

https://www.google.com/url?q=https://www.speedtest.net/&sa=U&ved=2ahUKEwiJ5IyG2c34AhUYD0QIHf1vAvcQFnoECAsQAg&usg=AOvVaw1lY754z1WsNxneOiDs7d3L

Why can't the extra junk be removed?

This addon is so convoluted I can figure out what it actually does

**Comment by Cimbali** [comment]
I’m not sure what you’re looking for? The link gets cleaned when you click it, not before, because we clean all requests not just links. Also this saves us from links being rewritten, e.g. google results with javascript enabled has `https://www.speedtest.net` as a link when hovered, but that gets changed to the link you copied when clicked.

The link you copied gets cleaned to `https://www.speedtest.net/` − you can test it on https://cimbali.github.io/CleanLinks/
