### ISSUE TITLE
CleanLinks is stubborn – doesn't whitelist

### ISSUE THREAD

**Issue by alekksander** [Cimbali/CleanLinks#23]
go imgops.com and paste:

https://upload.wikimedia.org/wikipedia/commons/d/db/East_Berlin_Death_Strip_seen_from_Axel_Springer_Building_1984.jpg

press start

CleanLinks kicks in and redirects to direct img url. 

go back and whitelist proper action

try again and see whitelist being ignored (?) adding imgops.com to whitelist manually is a walk–around

**Comment by Cimbali** [comment]
Can you try after whitelistibg, if it didn't work :
- see if the domain appears in the list in the add-on preferences
- reload (F5) the page that causes the redirection

**Comment by alekksander** [comment]
it does not appear in the list in the add-n preferences (therefore f5 doesn't help)
this is reproducible under fx 59.0.1 and nightly with CL 3.0.2

**Comment by alekksander** [comment]
i think i found next bug that relates to this issue.

go to:
https://www.youtube.com/user/NiszowaTV/videos?disable_polymer=1

and try to see thumbnails. whitelisting youtube.com, and i.ytimg.com doesn't seem to does the trick, it still filters i.ytimg.com content (as popup indicates)

**Comment by Cimbali** [comment]
There were a bunch of problems in the last update:
- Parameters were cleaned but not per domain, so this was not ideal and caused some sites to fail loading for perfectly valid URIs.
- Some links were added to the cleaning history without having been modified, simply due to URL encoding differences.
I've reverted to a previous version, and will re-implement these features differently later.
