### ISSUE TITLE
mozaws (firefox add-ons website) redirects support

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#36]
Here's an example:

https://outgoing.prod.mozaws.net/v1/fc3d342353d59cca18b6b696e5afbdf37f6a5c0d5d209b7da2226932ff2e517a/https%3A//github.com/Cimbali/CleanLinks

**Comment by Cimbali** [comment]
That works for me, it redirects cleanly.

If you mean that when you are on AMO (addons.mozilla.org) the redirect isn't displayed, that is because Firefox protects these pages and forbids any script injection, thus we can not display the cleaned link in yellow (or whatever colour you configured).

However, if you look in the cleaned links history, we do catch that link cleaning at the moment the request is made (instead of at the moment of the click as usual) so the redirect is skipped anyway. You just can't intercept it early or show visual feedback for clicks on AMO.

**Comment by birdie-github** [comment]
You're quite right - Mozilla doesn't allow add-ons to run on Firefox add-ons website which renders this bug report invalid.

It ostensibly works except it doesn't because I see mozaws in my browser history.

**Comment by Cimbali** [comment]
I'm not sure which "it" doesn't work, the redirect cleaning or the add-ons website protection.

If I go on AMO and click "Homepage" I come straight to github. If I try it again with the extension disabled, I get stuck on the outgoing.prod.mozaws.net page, with a message that says "Firefox prevented this page from automatically redirecting to another page." So the addons cleans the mozaws page regardless, as it appearing in the cleaned links history also shows.
