### ISSUE TITLE
all settings fields are now empty and cannot be edited...parsing bug

### ISSUE THREAD

**Issue by FredThompsonII** [Cimbali/CleanLinks#47]
Adding `|?Expires` to the end of the default "Skip Links matching with:" field will render all fields unviewable and uneditable.

I'm using Win FF 56.0.2 Nightly. 

I added that exception because Clean Links was scrubbing time-limited media links and this addition should fix the filtering, however it broke the display.

So, how can this be fixed?

**Comment by Cimbali** [comment]
It's probably a bug parsing the regex. We should catch the error and display it cleanly instead of saving the erroneous regex and crashing everything.

Does the reset button at the bottom of the preferences page still work? Otherwise you probably need to uninstall / reinstall the add-on to fix it. After I manage to get a fix out we shouldn't need such a workaround anymore.

**Comment by Cimbali** [comment]
@FredThompsonII If you haven't reset the preferences yet, you can update the add-on. That will fix the preferences that can not be edited.

Then, to add your exception back in, add `|\?Expires`
