### ISSUE TITLE
"Copy Clean Link" menu option missing in v3.2.3

### ISSUE THREAD

**Issue by Cimbali** [Cimbali/CleanLinks#59]
Reported in #48 by @toughdiamond

**Comment by toughdiamond** [comment]
I should add that I'm using Windows 7  (32-bit).  The option is still there on a friend's Windows 10 computer, using Clean Links version 3.2.3.

**Comment by toughdiamond** [comment]
The menu item is back in v.3.2.7, but Clean Links doesn't seem to be cleaning links at all.  3.2.1 works fine for me.  When I click Copy Clean Links in 3.2.7,, nothing gets copied to the clipboard.  And there's nothing in the "last links cleaned" list  - that whole box is empty.  If I click the Windows Copy Link Location instead of Copy Clean Links, the link does copy to the clipboard, but it's not cleaned.  
Don't know if this is a clue, but when I use Facebook with 3.2.1  I don't see any pictures accompanying the outgoing links in my newsfeed, but with 3.2.7 the pictures are there.  I've never been sure if the absence of those pictures was a bug or just an indication that Clean Links was working.  I used to get the same behaviour if I disabled Clean Links 3.2.1.

**Comment by sergeevabc** [comment]
Windows 7 x64, Firefox 70.0.1 x64, Clean links 3.2.7.
“Copy clean link” context-menu option is present, but does not work on any site.
@Cimbali, could you reproduce that?

**Comment by Cimbali** [comment]
@sergeevabc I’ve seen that as well. I’ve honestly been meaning to get back to advance this project a little but I’m short on spare cycles these days. If there’s a quick fix I’ll push it through but I don’t have time to make any deep investigations before another month or so.

**Comment by Cimbali** [comment]
Thanks for pinging me on this ! Fix was easy apparently, and it’s already out on AMO.
