### ISSUE TITLE
How to support Google Chrome

### ISSUE THREAD

**Issue by xljabbber** [Cimbali/CleanLinks#70]
How to support Google Chrome, please let developers post

**Comment by Cimbali** [comment]
Hi @xljabbber, your question is not quite clear. Also I don’t use google chrome but the extension API is very similar across Firefox, Google Chrome and Opera. Here’s a page with the main differences summed up: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

Most likely you need to change `browser` to `chrome` (or simply set `let browser = chrome` in `modules/prefs.js`). Once of the API differences that we rely on is for `onMessage`, where we always respond with a Promise instead of using a callback, because [this latter option will be removed](https://github.com/mozilla/webextension-polyfill/issues/16#issuecomment-296693219).

Feel free to reopen if this doesn’t answer your question.
