### ISSUE TITLE
Guide to whitelist?

### ISSUE THREAD

**Issue by Swizzler121** [Cimbali/CleanLinks#90]
Ever since the latest version, it's breaking nearly every site I visit. I've tried the information you suggested here like reset rules, but I'm to the point where I need to figure out how to just whitelist a whole website, or just drop the extension all together. Is it even possible? or do you have to whitelist one embedded url at a time? Because on some websites (like gmail) that's not even possible because the website is glitching out and redirecting constantly until you shut off the extension.

**Comment by Cimbali** [comment]
Hi @Swizzler121, the goal of this version was to allow finer control of what’s allowed or not. I’m afraid there was no real way for me to gather the rules for websites I don’t use, so I’m sorry for the extra overhead this update has brought. However I hope this will stabilize soon! There were a number of reports of rules misfiring but this has somewhat calmed down.

I have found that when I made the rules for gmail I accidentally made the for `mail.google.com` instead of `mail.google.*`, which means they won’t apply to google with different top-level domains. I’m fixing that now and pushing an update to AMO within the hour. When you have upgraded, gmail should be fixed for you too, as for #82 

If that does not work, I would be very interested in knowing what goes wrong for gmail (which requests get redirected wrongly), as that is a widely used site, and it currently works for me. I know that when it did not work, it caused the current tab to reload constantly, which was very annoying, so sorry again for the inconvenience.

In any case, to whitelist everything in gmail, you can make a rule as follows:
- domain: `mail.google.*`
- path left empty
- whitelist query parameters: `.*`

This will effectively match and protect all of the requests to `mail.google.com`, however I remember gmail requesting from another domain that was `ogs.google.com`, so whitelisting that domain instead might fix your issue. In fact we auto-detect when the same page is reloaded and allow it, and we auto-detect when the current URL is sent to a different page and block it. Gmail does something that’s neither of those: it sends an URL that’s from gmail but not the current page to another page. That’s why CleanLinks loops.

**Comment by Cimbali** [comment]
2 other things:
- resetting rules removes all the rules you edited by hand. Be sure to export them first if you want to recover them, you can then reimport them from the same json file.
- writing a guide on how to whitelist would indeed be a good idea. The next release is focusing on improving the interface (and is nearly ready), I’ll focus on this guide after that.

**Comment by Cimbali** [comment]
v4.0.6 is out ! Please tell me if it fixes your gmail issues.

**Comment by Mike-Reddick** [comment]
I agree, in future CL can have a little documentation, with some basic examples and explaining each feature better, each control of painel etc.

**Comment by Cimbali** [comment]
I’m currently writing the [wiki pages on github](https://github.com/Cimbali/CleanLinks/wiki). They’re targeting directly the v4.1 interface though.

Please feel free to have a look already, and tell me if you find anything that is missing or confusing.

**Comment by Cimbali** [comment]
Closing as the wiki has a good start of documentation and v4.1 now points to it from the settings page.
