### ISSUE TITLE
Unable to change/revert/remove built-in rules

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#94]
Speaking of bug #91.

I click the X for "feature" for "youtube.*" domain. It's seemingly removed.

I close the extension or refresh the page and the "feature" is still there after I open the extension options again.

Edit: it's even worse. I've added a string to `whitelist query parameters` and it's **not** saved either.

Is there a **Save Options** button somewhere which I'm missing? I surely don't see it.

Edit 2: I needed to click "Save Rule" above. It's super counter intuitive.

I really believe the extension must have its own window, not be embedded under extension options - a very small window which is too little for this extension.

**Comment by Cimbali** [comment]
Updating the rules more “naturally” i.e. without having to click “Save Rule” is problematic when the domain/path are being edited. When adding a rule for which there is already another rule that matches the same URLs, we want to merge them. However if this was a temporary state while editing a rule, then we would need to somehow un-merge rules.

I’m trying to come up with some way of indicating that the rule editing is not finished. We can’t show a warning when leaving the tab with unsaved changes because they are preferences. Maybe another page is a good idea indeed.
